version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  heroku: circleci/heroku@0.0.10
workflows:
  build: 
    jobs:
      - cypress/run:
          yarn: true
          start: yarn start
          command-prefix: yarn workspace client
            heroku_deploy:
    jobs:
      - heroku/deploy-via-git