version: 2.1
orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@1
workflows:
  build: 
    jobs:
      - cypress/run:
          yarn: true
          start: yarn start
          command-prefix: yarn workspace client