version: 2.1
orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@1
workflows:
  build: 
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: yarn
      - cypress/run